export const AXO_TOKENS = {
  pageBg:          '#eef3ee',
  surface:         '#ffffff',
  darkGreen:       '#0d4a2f',
  darkGreenText:   '#d6f0e4',
  buttonGreen:     '#1a7a4e',
  mint:            '#d6ede6',
  mintText:        '#0d4a2f',
  mintSub:         '#4a8a6e',
  salmon:          '#fde8e0',
  salmonAccent:    '#e05a2a',
  salmonText:      '#c04a20',
  cream:           '#fef3d6',
  creamText:       '#b8860b',
  lavender:        '#ece8f8',
  lavenderText:    '#5a3d9a',
  bodyText:        '#1a2e22',
  subText:         '#5a7a66',
  labelText:       '#6a9a82',
  border:          'rgba(10,60,30,0.10)',
} as const;
